### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by nblackburn**
Tested manually and working fine on 1.5.

### CODE REVIEW

**Comment by cebe** [comment]
`~1.4` does not exclude 1.5...?

**Comment by GrahamCampbell** [comment]
Yeh, this doesn't need changing.

**Comment by hkdobrev** [comment]
I'm sorry to say this, but RTFM: https://getcomposer.org/doc/01-basic-usage.md#next-significant-release-tilde-and-caret-operators-

About the caret operator - basically `~1.4` and  `^1.4` means the same thing, but `^` is more accurate regarding SemVer, so I guess in the long run it is better to use it at least for educational purposes. In short we could change `~1.4` to `^1.4`, but there is no point in increasing the minimum to `1.5`.

**Comment by GrahamCampbell** [comment]
It's fine as it is. It doesn't need changing.

**Comment by cebe** [comment]
@hkdobrev `^` only makes sense if a specific minor version is required, `~1.4` and `^1.4` are equivalent.

**Comment by nblackburn** [comment]
Going to close this as it wasn't designed to be a debate.

**Pull request closed without merging**
