### PR TITLE
Fix tests and update for compatibility with upcoming 1.8.0 release

### PR DESCRIPTION
**Pull request by aidantwoods**

### CODE REVIEW

**Comment by PhrozenByte** [comment]
Also see #96 (it's the follow-up to Parsedown's new `CommonMarkTest`; however, #96 shouldn't be merged as-is, we should rather use Parsedown's current `.travis.yml` as a basis)

**Comment by aidantwoods** [comment]
The tests still fail here due to the core library no longer being vulnerable to XSS ;p

Looks like some AST/text boundaries were "abused" (read: taken advantage of) to insert footnotes. (Similar to what I alluded to as a possibility in https://github.com/erusev/parsedown/pull/495#issuecomment-298717654).

I think it might be fixable without doing this, but it might be beneficial to refactor the core library to pass around the AST instead of a HTML string so that everything concerned has proper access to the AST structure (instead of trying to read it out of a string as HTML as is happening here).

**Comment by PhrozenByte** [comment]
The infamous side effects of fixing bugs and security issues :laughing: 

I totally agree, it's better to rather do it right than creating the next workaround. Since Parsedown Extra never received that much attention compared to Parsedown there are some more conceptional weaknesses we might address in the mid-/long-term (e.g. how `<div markdown="1">` is processed). However, it's probably questionable whether Parsedown Extra has a future as official addon. If Parsedown's CommonMark compliance matures, we might get to the point that we simply don't need Parsedown Extra anymore (e.g. I personally prefer CommonMark's way of including HTML over the `<div markdown="1">` solution)

**Comment by aidantwoods** [comment]
Completely agree on the `<div markdown="1">` front. (In-fact that reminds me that I starting on something in the direction of CommonMark improvements in this area: https://github.com/erusev/parsedown/pull/489).

I'll try take a look at swapping the HTML markup string for the AST in Parsedown tomorrow (unless you get there before me ;p). It would require decoupling the handler delegation from the HTML renderer, so is probably going to end up being a fairly large-ish change.

**Comment by PhrozenByte** [comment]
> unless you get there before me

Undoubtfully you're the expert, you take the lead. I think I rather go to bed now, it's 2 AM in Germany :laughing: You did an amazing job today, Thank You! :+1:

**Comment by aidantwoods** [comment]
> I think I rather go to bed now, it's 2 AM in Germany 

Heh, it's not much better in England – only 1h behind you 😆 

>  You did an amazing job today, Thank You! 👍

Thank you! 😃

**Comment by aidantwoods** [comment]
A few notes on the latest commits:

* Changes to test cases are whitespace only (due to updates in how Parsedown now outputs elements)
* There is a very hacky fix added to get the tests running – we should probably fix this properly
* FIXME: to remove `dev-master` requirement from `composer.json` before the next release of Parsedown-extra, and after the next release of Parsedown (1.8.0). This is added now so we can get things running with the upcoming release (since we're broken with latest anyway)

**Pull request merged**
