### PR TITLE
Fix PHP 7.4 RC2 incompatibility

### LINKED ISSUE #134: PHP7.4RC2 incompatibility
There were a couple of errors with PHP 7.4RC2.

**`Trying to access array offset on value of type null`**

### PR DESCRIPTION
**Pull request by storeman**
Fixes #134

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
@erusev could you please merge this important fix for PHP 7.4 compatibility. The library is totally unusable on PHP 7.4 otherwise.

**Comment by erusev** [comment]
Done. 

@aidantwoods can we create a patch release for this change?

**Comment by GrahamCampbell** [comment]
Better to merge in the travis stuff and fix the tests first.

**Comment by GrahamCampbell** [comment]
https://github.com/erusev/parsedown-extra/pull/141

**Pull request merged**
