### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by erusev** [comment]
@GrahamCampbell Thanks for this! Could you please elaborate?

**Comment by GrahamCampbell** [comment]
I've updated the config to test on all versions of PHP. However, the tests seem to be failing for an unrelated reason.

I dropped HHVM since parsedown doesn't test on it, so little point in testing parsedown extra on it.

**Comment by drjdr** [comment]
@GrahamCampbell fixed in #142 , the test also requires erusev/parsedown tests. The 'test' dir is not included when using the --prefer-dist option for composer. Thanks for the great initiative on this one!

**Comment by GrahamCampbell** [comment]
We should probably fix the .gitattributes of parsedown so that the tests are included with dist. I'd say that's a bug.

**Pull request merged**
