### PR TITLE
Fixed PHP 8.4 deprecations

### LINKED ISSUE #184: PHP 8.4 deprecations
[PHP 8.4 has deprecated implicitly-null values](https://wiki.php.net/rfc/deprecate-implicitly-nullable-types).  Until this is fixed, deprecation errors will occur in Parsedown-Extra.

### PR DESCRIPTION
**Pull request by davidbyoung**
Fixes #184

### CODE REVIEW

**Comment by davidbyoung** [comment]
@erusev Is this repo still being maintained?

**Comment by erusev** [comment]
Were you able to run the tests?

**Comment by davidbyoung** [comment]
I did on PHP 8.4RC1 on my local machine, and they all passed.  It's a backward-compatible change and that just makes the nullable parameters explicitly nullable.

**Comment by davidbyoung** [comment]
I've pushed an update to fix _some_ of those issues, but likely more are needed.  For example, we should probably add PHP 8.4 to CI and allow it to fail (it will until things like [Psalm](https://github.com/vimeo/psalm/pull/10928) and PHP-CS-Fixer natively support PHP 8.4 without having to use things like `PHP_CS_FIXER_IGNORE_ENV=1` to work around their lack of support).

**Comment by erusev** [comment]
Do you know why we have 3 branches?

> CleanShot 2024-09-29 at 17 39 17@2x

What's each branch for?

**Comment by davidbyoung** [comment]
I'm not sure.  It looked like 2.0.x was more up to date than master (eg it had GitHub Actions instead of TravisCI, it separated code into the src directory), which is why I rebased off it for this pull request.

**Comment by erusev** [comment]
Hm, ok, but if we're making a release for these changes, shouldn't it be a `0.8.x` release?

**Comment by davidbyoung** [comment]
What's v2 for, then? Its most recent release was a few years after 0.8.x.

**Comment by erusev** [comment]
It's probably a version of the extensions that was designed to work with Parsedown 2.0. It's something @aidantwoods was working on but it might be abandoned.

I'm also not sure why `0.8` is a separate branch from `master`.

There's a discussion about the same thing in Parsedown at https://github.com/erusev/parsedown/pull/881.

**Comment by erusev** [comment]
@aidantwoods can I merge `0.8` into `master` and delete it?

**Comment by aidantwoods** [comment]
It's been a while, but I think parsedown 1.8.x (and extra 0.8) had some risk of breaking extensions due to internal changes to escaping HTML. I think I put these out as prereleases because I wasn't sure what the BC promise should be for not breaking extensions (given they hook into a `protected` API surface rather than a public one).

**Comment by erusev** [comment]
Do you think it still makes sense to have that branch? The latest release, `0.8.1` is almost 5 years old now.

**Comment by aidantwoods** [comment]
If we're happy releasing 1.8 as stable I think there's no need to keep the separate branches around

**Comment by erusev** [comment]
@davidbyoung Can you create a PR that fixes PHP 8.4 deprecations in `0.8.x` branch and also adds a GitHub workflow for testing similar to the one in the `2.0.x` branch? 

You can also use the GitHub workflow at https://github.com/erusev/parsedown as reference.

**Comment by davidbyoung** [comment]
Closing in favor of #186.  @erusev There was only a single deprecation I had to fix, plus I had to pull in some minor changes from master to get the tests to work.  I don't have permission to actually try running the GitHub Actions CI, so you'll need to approve that workflow when you get a minute.  Finally, I didn't re-add all the tools that were in v2 of Parsedown Extra (eg Psalm) as that felt out of scope for this particular fix.

**Comment by erusev** [comment]
Merged. 

Should we also make a release? Let's say `0.8.2`.

**Comment by davidbyoung** [comment]
> Merged.
> 
> Should we also make a release? Let's say `0.8.2`.

Yep, sounds good.

**Comment by davidbyoung** [comment]
@erusev Can you tag 0.8.2?

**Comment by erusev** [comment]
Tagging it as a patch (`0.8.2`) is probably not right because it now points to a newer version of Parsedown version, and this feels like a breaking change.

We should resolve https://github.com/erusev/parsedown/pull/881 first, and then make a release here.

Does this make sense?

**Pull request closed without merging**
